project:
  create: false
  name: gepaplexx

applications:
  ####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-update-checker
      targetRevision: "*"
      helm:
        parameters:
          - name: "clustername"
            value: "steppe"
          - name: "consoleUrl"
            value: "console.apps.steppe.gepaplexx.com"
          - name: "slack.channel"
            value: "AgBIPG9Zo8SxwkZbayJT7kKCFT8EETzn6qmwPLmV3H9KOgxUWsPdhKQZC0Qnkc6dGJk7jv/rDhnzzYJ62hSvIvgKh5FQQkOyIbAvWhIUeO7xSWQK38UhULmlIdnhMoo1NVbmdWCM/VyF8N4HizqeD2c6UnTmJuwbWR7vGFzxD622G+arsZ4Kx5mBGnfcNsDcSu2yiq3R47m3iB+KNgr3M9aJFAsQaWHiiufgFTTqJicNAfo3FjzrPPvOd57B/SZuL0QXOlxUMVzHA/RGn5/2J+LWjnbOXH4d3d6zwmgv0mLAor86hn301y3ZLVXqUaphaMsPuVv8/KEEpTYu1uyw10cCMSr8wlCa53O7RdgA3IGdjHi0y9qZxs+HFzuRVhWOPmcADN3iUiJV7FZtW0C2N7HfdO3V1365D2BXuT23b4OzGplm2oj02XKeNAN9cj2/oWTVx4tSyojr9L/5tnwHlN+Sg21ACiqhRoAmQRe4K6YO+YSDne6+hE3aDPGAdNQQHUSHe8JHhaxzS9DiHj/R/5waLaSrm9TWlT2t1gDqehAN1aPra/QI+ETJtVAA+eapv5PUq7sWRyjTdEBMEOLbClIwRcHQKj/fslNhYEv0ZLAN0JeyBJwmsXtth89m5wVDPz+0WIeH2JbkBr3xLcYXR4OY7No+YA/jdtCDntyXH4GmnLIW55z7fE0MmbxtniT2ryHiiM4vrRhPC90nNJykMaxrBP9+Kc4HP10Gbnf7yGlXfuDzP1sWPpDtImPTe8GMpdGqXntLlnS0FXOGeMVNIoFfqxT5GGlNmZN5xuaWwqNhrIo="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-instance
      targetRevision: "*"
      helm:
        parameters:
          - name: "elasticsearch.resources.requests.memory"
            value: "10Gi" # FIXME
          - name: "elasticsearch.resources.limits.memory"
            value: "10Gi" # FIXME
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-monitoring-config
      targetRevision: "*"
      helm:
        parameters:
          - name: "alertmanager.config"
            value: "AgAs24uHwMiRim26NF9n6M6HWiYkU4IdAT8VzSnwsHlpC+jBjOON70hpRE+Be7GIObFNwJ2thN9EO9Z6JUqj2U6wIVxbYku3nMXTzraFoIZQud8tI3OPE1FksBKb+ON2OTPmlGuQI9w/hTZk2JCcPmtdxEOfFetDvk/JBMGAc0nHnklOqJ0FW3WeS9mvA1XpBiz7v+X4qub0cSRxaTihAaZDGl9MY98FLtLLPvNWH6Io10tzwHm0f4LwTbCHd0/cBalTudY2I5ZFEbPs41ETdUjL/GrY8wzwTtgZIA/c0bSKi0hgWaB7a1gR3rtST6N+NT30F9gBoa5PD3iwO6WYnfP7Um3ZvEqix3EouBGvXciKp1ycWwlBUjNwU5g6js4Y//XYmBAxJKt4dEHcleHotsx+QIpaBhVg3QyaaqOmjAfvp1eV+w4Dd1PuiQ+HjUNO2XYKJmhOAqm35m16u6iT84h3MAgjup86qHWJMd9koGza+l5GgdDnEBgU5CBAQatKy2vTL9HowvJqHPesgV3i27MEHEK4adZqMVF7HI4fZkPWjaRmC7X1s6oJMXzNrz+ioiKuYjOif/75ERFuYSIW67JMdT/myqCQAhjw892N0rXT3DcvpqYaM7aWEc2ViqVRlOI6RR8oKwXqdtBokk3kxuUJzrWW3et9zELx4QdZ49gWGfjg+AN1JvZ42DXnXpGfllHOzBkGqZGa41Nd4eKnLPrMQQ6Pw9eRqDS9NRZlrMW/irA1uWo6LWxy2zoZBih5ZKRzIGCFIQzv7lvFIzhn9xs04l4FbZsBJSADTQMG2svMXLSUOA6+ZisrywYdKyQ69jG6wZj8x91WfTfxFK3WhU9OxjIVaBy0+bMftmPrheuVvpktK1lH0R43nFZafe6DThIzChIXGGjBvaHHEYADbiowavzdYy8fL85zQR+bovsyEdvNBBi3UvtMI1kHvdpoGFH8eu0eQ1s4WjitsF2CYTGXFUYD4/v7d3+ggfar6UIyXfNLlqmjvQwPFZ+F59Rg84bowVZ7sALR88bAZCv8hZ5nqAHQAcK8RW/OO7l298cegYjR3+sUzxOdIAzH/FyRT6v7tMlZqX7uAXT+8sfYcbLWZs5c7fxLD5bgTRaFQP2mhuCunrUE6otU8PpBualqc+eFvRYOx/hmmKOX7mETU7rfO2+5E2kbC01r0yRpqcolzvPuVAKTMXX8fT4h81CJjFqLza9LXjbz3yEKYdBSrCv43iAHr3UuZCM639jX+xsyGvqLd0eoGeICpntuU8BZbJiEStQOo8F4sKBHCRb+gecQ0l0fPWnoZjO5yLI4xiK6RSYkFKh2KrDeZE89krL5wBxzuaVce14x7GXJl11u9fL9pSk+od2gav5QZY1PbalLUxNQDoVZ7OedV7v8H3QO2H9Iu8TW/Tf41Uf+NrrtcBQ86wVEkBb8yrfy9H/pSzQC/nnA22taZhJInILnq+TJpF17J5LAclBNHwf3HLieQIcHr5vBasx6tmO+ATxIPrvq9D5dwZ2rE94lOD+iz7UEsUXkZ4LBbhbbJ8xvaw0W0/Ygp1Rl7xf7rFKky+SHKuPPsTy/+MBAntex26ShfzdrOKGpp9gzCcXGF7KV+agPr4jUoluk/OBS2cM4FDg2VvTcvkxQx3DNo9f+4qqAMkyiNYovugB17snbui13qw4QqkCAoXB9rGif6x6W8vsCbq/PJyQxvmC9E5zh3WY+46zrsGqICzwX20LstDSNQRtepqmfDTHegrVdIGCsqIftJkxHRdc4fHg/X2QV3dKfih8pAb8g62OPrt77Ck+UmNPSPkmghLIUNIDexpWw/sado2qSLB0/OQdBJN9YAEYeUbWMFulBrIZnC1STTVxEMIyEnM197F5yLmU+spM6ZrWbT3iYdYzFEPE2HS/tkWKYa4hES+6ThBKQAYd54LtzA9Uy0+dp1KU3xSPADZgTpjUkAzOXITamhZ8qnndubmIMhiAOsRHBIoLM0jHzOjJQaOfzF3ZErLxUJF4huiQQOkJSvIVjVutGQEO1477SqbL5d1yWgRT2xWtg28X5qyQ7L+f/PmrmV3864MvBfplDS0Z5I54M/Cva0JWyTU83m2tB+KWNE4y1AP2d2rIWAkD+CAJYDw9wHCJcVguqIBlBTa4GRlhssER1pVXv7WEoS1QKzuhb47p3SJhcSFWInJ3EtvZCAXAn/yJeSymGjDWy6eTO1cy8AmGmwUDVQEmFsUwr1Eq+Y36aOmTnTP/2BatG3Sn+hv7o4DQR/OZCH4t9aAuZkO58afIJJLypC69U7Sz3NiZj/0bfJpMBzMn9yQZlCB84DuJ2DsEfaIHT7Q9exvR66nc+/bdrxf4J2waZIPjR+x3v/4oExdKkSIs9WnVc43hTWSdXA81S53bf8uBBOUIfMpTTX94RiTveOrsc8hQ6zfTPNVU7vyekPHBRr8wwibhEF9g7vTnryxkHamu4hsU2iqSjEsabbEc08Ri4+kpAfIPSDbDsEexJTD70nettlYU4zbppsdgvmtSW+ishUWRZ6vAegWkFh1Rm03wZ5JIh2OyaXOOXTxZEwYwmzKbSMNDXTKCASwU/k2IKrKaJRl5teDVHLg4YJhsoq/JwrMlt1dklsRtk7JcjroxNLt81LAq6bTIjpizKUingj6VYm7fS6ViDlsU9NmgApK8RqbBPgno="
          - name: "infranodes.enabled"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-ocp-internal-registry
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.steppe.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.steppe.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "steppe"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
        group: apik10.kasten.io
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cicd-tools
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.apps.steppe.gepaplexx.com"
          - name: "argo_workflows.ingress.hostname"
            value: "workflows.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "sealedSecrets.postgresql.password"
            value: "AgBOMsWEqSwd6lxYLmAZ4WyGAboHcn3HT0D96ui/jcn6Vr4w9Vjw9MhEbKGw1YOsgby8mKptszRoMxmEnL5wk0lpUYlSuurad0fstLqqSd6NG+4vqAOH6vZKgaZ81jNmW7V/mHB+mVTN+6j99NATkKXeJzWoZmqC6Q5p7Ir/mxJxYpXmG2QJhmyAapsTfJJ3DFVBU7RZ20MJz3w5m8EYgbbm3WOy8B4OdOdaDHR8l8VE0zOO42QPn7fDsu/+fo/RrE4hosdWpiJrNyOGctgVd5Y6HSHENvl9swyObdDZ4NEX7vuAmP94TO9FIYIQbAVrzfWFGXsRdSBFMzNMl4GAopICbZuYPdvnm4UHRr4JS5+Rk3YljsVccAtzpM9LCDcR9tpSVEezaBE8UZS3qgzSCklO3yjxl3lSqIpyqzIMCsKyYmZYjqxDfQqD4uB1K8CnDujjQ6ib6pkf4/jckzD0/LW5SvjsUK5+m7PeG9/BgNv+V4Y4CHUhzSH/nt/Wjz/t4LSkWyzK4o7GmDKIPgfErOawELnqYTbdNdsBMALGKK9luSAsaod5PGreBKGdqe5qTCaOhUXfqm5a01hwwpV7LXGaznwI1w1wc2oIYM5lR0biH9F42c9+l4af4Hq8Ed8+J6i0vu/tf0RlzRvH6JpjM0I/poE638FaCCHrPaSwGtDurPKKHNOsJ6clpoxUidhDkqz1rOrE/AX+crU="
          - name: "sealedSecrets.postgresql.postgresPassword"
            value: "AgA1XBm6eO5U4WcEKxom15GxeO7wpWJlYZ2HG7zVnPAH54kh4vsTLpzLm0Pr3GjRYEKU7sRa7i8QJH/ZVEyZKD+fYogafKETCmcq9PEIhg+iK82UbSmxI5I1knrx88llzVw1u3xa3huXXLfNAFQUFO+c/2xz11zaqjOym531uvYMgA1ZCMo01YqHrzYj+tEhLGvZO8xVQXCWvmam8f4ziMGO9lShJF7I3WY6sjk7pL5pFOCoRltUZjboYfbiGh7LPc+fZIdC3+68xFg0XYCBlI2tg5cdLKuHeRuw3KGCfQaTVQmbhFUYNJML+f6ph74ZoJuXCRjWM1g5AWxBb7JGqrZ+mwI4rh5LvbFw17MsPwLjQLW5pqu+/P2c/wYvbNadrSp4o2e++qvKIgc4L4sOOz2iehSsHDHMOOlFS1DsD2v6LGjDW+qBkWLN768OUy4kbQVs8VeyKNAc/fYvP2gx5Tox4hnSQzIfdD27y/I0EXCpZeB7otLT9ZtgYhtbfOVByry4L++EP4maoBaT1BS4cDmeYORZwZPooCdSPtYGYcEn/bGVRYVIMVXiaD0blwW7haN6yf8tLYTp4gaS4RBoVa9EqNAguDMj6kvqCg0iSlfCU8XVrOLBY+zGelBolz/sshRk6UAAJzMbTjafysnqfDTvDfvZy1yzHJG2lDqKslc7JerOjnY5CQMTiHONChUVh6grNcXq3rwKWcQ="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTS ######################
  gepaplexx-cicd-argo-events:
    name: gp-cicd-argo-events
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cicd-argo-events
      targetRevision: "*"
      helm:
        skipCrds: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/steppe/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true