project:
  create: false
  name: gepaplexx

applications:
  ####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-update-checker
      targetRevision: "*"
      helm:
        parameters:
          - name: "clustername"
            value: "play"
          - name: "consoleUrl"
            value: "console.apps.play.gepaplexx.com"
          - name: "slack.channel"
            value: "AgA0ym5EyLQjaqkepc0IEYUruXnlAorIZocs6od7bs2pvEh0Mo9Ij+QITnjan3ImMxHVM9S5Le7PK3hsXIJTYibsJy1CRfahO1STCFhlpqXyhvkjpm9HC2q7vI3+CnoTWT8L8RbHFg9BTEYh7hfh9MBfy1W8yRFy4oq16K9V0HQB9ah+jkN02IMhcf6mHxu8Yfa1bRRvOZfbTFuBrLZwawZTv52vOB04zOjyRNBeb5RCel/pbah5GZKQJI+gO5JdX6iObOjIdOtGFvkllGTo8GPgsRFCoEAXqafBLm+5J20kNHT5uZl59tLybLOEzfKTipvm1f+oKBQXoxXVN41zuJcp49Pl9eLBXpEqfO8p4clyX4YWYNl5es2GHEnmbVXyKhgwlpj8xNp4anT7iU4zKXV+mpTbiaCHnaZOAXD0QaVQcxdkwjkDYMrdyP1mne3iK0fMuUMww2+WzXuW7ZT7RWGTrFAR91emdSppCU5VMD0HS8ZsxFGdqIQlYUn5XJWE6SYbQAUku1gp1ayD+kYrjPV0PWekpvcGSIw+IdiYmds8ov1+7pr7X9Dv8ccTv6CXZMqPlQiJ4BPiVYdZyYU2fQfvBQQovXSKhp9RkmcEyZ+dvG3lGjoGjBdgemMK58YgtJzcidruFAR/BuAeT/2+nTrq5sHcFtnElb4wYvFDmteV7Htcts5RurN87p+bNS9+azYvsIuJQNg7f+fmMklMyM2EKp6mzu8HEybm9BiBzerRasaUnx4F+qNKGHQKbTu63EMYo2HqP2zQXOrDZtAPc2cnpUTx8lURk/8PyE/q5MC5cMc="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-instance
      targetRevision: "*"
      helm:
        parameters:
          - name: "elasticsearch.resources.requests.memory"
            value: "12Gi"
          - name: "elasticsearch.resources.limits.memory"
            value: "12Gi"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-monitoring-config
      targetRevision: "*"
      helm:
        parameters:
          - name: "alertmanager.config"
            value: "AgBTIaR9dN1dxiA3gqkrc8TjfFkvRtUmGSJBcl33Gi5XTXfDAxU3wSb0MYlhznwSIjf7b8CWIR3yXKS2kXJ/7dWcnRjOvJ9ThlFMjJa88tdua3q2NC4t5doepVsWsiSrvpfHmTcyX99U5gcdePHgKBUNCyyTNCMFZroNGDabFHhmUlT3OW8waQsrEwXAYr7xR8LVS9L6RErZFRrwb0PCqEWe1JdaSVX3AWvxrJRQtGwkCtK7syMfzTX4wfrOzeKV1pNMKge9f4m4+Cpxu/BOzbwEZXcnAWBTcCGu/ztrSQrh1t5isWRQnmRDmBmZoaxc7MdZdqlB3R+ymHSeh/I6Drju0fvWhkH4qeANn03r4ZeIKGfLBsizJCPdBzpE7K6sQRtJt8OlwKT/piSDuTo/9qUByfDdy+/LKm3vqUe6AigyZeX2WQ1/Jhlq1lOExZFk8yDpqgE+XRKbn0Aazj42GulBNs5pw2+U53JGWZbPQuHh1Eu7fCMy02qdFt+o9++IsOigntzB/2FtW8hYxWPMhvqk6+3O5xt0VGHrWzKG+vh5myO2YKvn7x4DcnLyNfrPiM9ZGsEaWi/8XfyNlix+9dmtajfOvZgkQRwpIPHwfSx8WXQnMUqXYVDq+F+m8fNesjj6qu2VENIncU7ovh636NB6FSXrMV7cQJMV42hDnSBtHXw+2XPWEkK3kV/IcF/dRxK1SZFg87qAKjCDVUAKcVPTknpPNHAMT0gM/c81DiJWFGb3fW1tcHudolH1MilqMfi5kmbbCVEYFmX1y34kv8mIxKVUVgju2aWULiNmfbhs9ItQj9nIhHqKvugOaZvXLhpxU7vm9TkoQJvulryOxEMftZ0WatIIc1wh+obqZKesj2smqkfd5xUUZ6C3F2AeYmrzXye8T9xW8zSdAs0tAcTtUtflTgvNerk4XfKbAr4EhwiGaiEdRsqX7Yvnz7LO5BqUd0vvYvEaO7gJIHWTC9znLOjSQ8TW0mhHAsEs93ZfSUod6OJLlSiv/GfTcW7fGVRno5uwbOHt81yAakPUl1yAe8nKLrKF46+QjGUC1TcPCUFVjP85mHdedyKIQ7GFjmN5+7W9SzC8KuPrLH3eKGIzNYIqUG++J29QfG9Aw++496LkZnHKfRCgSbCfyPKGGU8Mh2nquT3gkTX2kL7UivrztrZWLWU8TL00YJuRwyY+VVOAIoCQ+sVeuNiOorG13+Be9kucMy9lt8pppPVYKY10d6RMM3KtIY83foN1L3HbLQKSt1nhQAGmz7itNVb6Nv8gTB9SOR6INbfrR4OTeV2VBTcr4FeTBq+/ZLInXU5/yCjbq8OEPeNW9Aohl2Ac1o8dfuBpHSZq7Mpg1Nt3WE9xTUGP5UBjknUTvuOfCB69ZjmoVXkOMfbMG4Elra0sT9JVK/YuKn/ywOrMwnbs2z4gFx8xvq4m5cGymR34hJitVa8kM9jnwTWom1+383yYkVGMR119u+VYwnArwrNulyfOEc/81gvEDMuzl8EyeLNJzM1huN3Rcwj+ePKth+ppHKMFdK6zDOBK3Y6TEOzd5Uphc2dxZKAgx/jqBp0J6NzZAYcyrPzFF6fFWZDB1RG08auGrsYyC5ImUG4GcOK+Hcvq3IcAU29CfQl2Ipc+2nlVJPIZXpBnfNFVvvCNfe2h4xhHHsIdviyrz9PNai/By1JOVmRt/XKcDjhUUkjU1k6XIYPvpfXfsK/rfh9nbT8ippRXcL0j/wD5icJ2U4ZEkY6wkBXQ+c7CRPMjg9ZTmY4eH09oQhTGFwyJ+VP6KmMJDIJwCGoB56Kh1gL2nww/P/MIzTYtQ4Fa/vevFoQrbog7cS7NOHtYH1SkJViTk92AgUwdhdhU3a1BdPHx1WH4+7jBPJhHsf0ZR32RMdiK95J/V67eolGuftQzr4k2e8Yi9R9Y0MQX+K/hyifXMrr8BazBr/qUb2kRCa9x4uyqHRj1TSGGlH5ssgO6M9OVRVkLH5VU48AKzcl2WkIGblmCw4VyRCQSFT8DLxwE/7aZUWd8Ie1CrtffG3ButSRPRv78fYMSZglJEf/1YWUd45v2ujjP0M7CDSzEpVpEPrKmNJ7KZ9seRPl5pX838Cr031M5GrWA1Mbmc4TKrziVnRV6kuanBaPV8yaWggL2d6ytO201D6IX0Xx8q6hKNYCRvge7Bztd8qLy43Bw7diO7ilDPyztnB9jywLjSfVDz94m1GOCL2iW6ucLJ/SdXXozdWN1Uj2gmHHkVFDRaDGKJ5TUnt0ShLZ6c1h3ffs5CIAcdXmTPAAWcNjd3Z9YxSywYRwDc54mWm4bCjtMvVPwXi3yaCNw2LyGd4FjL7Cz4v3m5/4fGGfCp2akeqC5mjZ5XuXCiLxTB2ASFbG9sgqCa6DIyacWmVzq1Mj4a7alAk7E+gkfR+nEKyidiFlrVaMlb1h+Jy/t83BglCWjK0iLxyTPCU1/q9DHlEm9DmM3erT0fZYRo9tDXtFywoYA3yAjDC745wMiVV23he5IID1Zuy+FtvaWqbfRVNK5xrxMUuFlTpyTkmtKNjNRSkFARSYB69/SgZLgHODGNOSoSaVvadk8HDwViZ5+kVq74TY0a38l2qLZGyXWEF7HlU8n47wik2PMwR4gfVdURXWCxCErwtkBoAm8q7nhj/qTbUzyIp2+0GJy1tjU6ZKiDLAIfzYwO98="
          - name: "infranodes.enabled"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-ocp-internal-registry
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.play.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.play.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "play"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
        group: apik10.kasten.io
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cicd-tools
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.apps.play.gepaplexx.com"
          - name: "argo_workflows.ingress.hostname"
            value: "workflows.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "sealedSecrets.postgresql.password"
            value: "AgBhumWZjXDQTmgIpPXhmFkYiBUP+bKfC600hiTBnnsZS+PA4FCTOwDexNpow9LId5lOxFevjstT6+g2qXAFibSQABmZVeC7XwceH52tHZuAKiOTLd2AQYcP2HGJAZqvtj6DO2/7slW7DRJf3dMzFI6Rra24u9j2o88O+5X5jzVKZWUhNgkEw2qlBVwlasV8xaG48vLv7AFLDPK3FtYbvlPNYSWGUfUXwrPNLdI3C/mI+RzCoSnKpqYEyUGKqsA13AUvvYU32A0QV8dZWts3wy1WuhY9Oy59Ad06iJ4wMB5ifjdyYo2F0AggQiAx+1kHwL7LNazlSpYBpR5vsVKB3COvcboxeTlTgcfKjGyu/0Q/eKyslXkNE5StMGABWTAljR/oIsXqGuh/NHsZzGA2KVKIagKhrY1UCEA8Yl0TdlMT5MfdTsnrUAiLxh0v1iLS/NCFm8Px1ne/OnMalpEq9kdpgM0nbIKx5/R5jbGUr93vvFBEMygAC+U8mE6cHSfzeejDgQSxsWLInXhz2W+q/bTGG72tQYizJwhFRcEkr3qAtcjI2Es6wyXUL1RiXLaKDftjxRnwkZ6VYnsbTN4H+YDUX8+J8d/r94SCxq/Sp5MTVetJ4DCisOCY0KwSOHVe7EPcQE0XXHfClKjUzGV8JrlmgJ8D6SwFToHRxihrGlZlOj9NftHL1TH1gYuQJngDHDqJNVzYHjdywHA="
          - name: "sealedSecrets.postgresql.postgresPassword"
            value: "AgBVb2XmJqmRQsYn3WkjKODRBPyQt6HCGtlpmr6dytW0kG94cAEeIX21TNn1QDLhskDEUww3xyEV6iUOx5m6IXtVtpL8STVE72QSdtIl6EUii5LJqJoMDEgYUZrqtFwjTPtKuDJdbvox0pCmDWmv2/v5lsYrq1FYoGQWmuY5nlUy4Ec6jx+bOc2XZM7dWwmV4A9iMJXZraJCx4240YNfZYEfJLwmFaYjCSugEqBQSRNs9S4gWFRi17ovNBHLh4iXwgF1oXHg9mlayx65E4ON54rpwFnvqA6ODue6tsGJbiY0gDiXup2ai6Nlap2mRKCtM3+RFaz/2E/8Mu8fcmBOmDXiGVnStLCxkq/c6cqB8bSTeG7FKZ7MiTLCdxOrDebGJEEeyAh5ulheaBt451Wfs+SnSpl+cL80LzUHS4gVSSSxhofpL0O6qTHmDNBFtdhaPUxwa3VERkgWwpCy0wQqFimn8/J2yGeGFSvrqn9kNIxoWQIQcujFPTkAoj2zwXbYa1vWHPOklBJYsPBA75T8o8Bgujn30/DLNf+1X1TpMl9mc02MV5BDNY0bCz2XaDI9r0bPgAp7HOfq2/TMYCkfu5znT0pC4yQ/DfodQ72HTJsYx6CTimN3IPmLVqmHTycLohj8zc/mnvYRtLp17smvgGk2g/BTQZQjleRR3ORFhRZeh7g8MHiLjrmhxj7NmoWIech+guxrKTRosAc="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTS ######################
  gepaplexx-cicd-argo-events:
    name: gp-cicd-argo-events
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cicd-argo-events
      targetRevision: "*"
      helm:
        skipCrds: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/play/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true