project:
  create: false
  name: gepaplexx

applications:
  ####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-update-checker
      targetRevision: "*"
      helm:
        parameters:
          - name: "clustername"
            value: "play"
          - name: "consoleUrl"
            value: "console.apps.play.gepaplexx.com"
          - name: "slack.channel"
            value: "AgA0ym5EyLQjaqkepc0IEYUruXnlAorIZocs6od7bs2pvEh0Mo9Ij+QITnjan3ImMxHVM9S5Le7PK3hsXIJTYibsJy1CRfahO1STCFhlpqXyhvkjpm9HC2q7vI3+CnoTWT8L8RbHFg9BTEYh7hfh9MBfy1W8yRFy4oq16K9V0HQB9ah+jkN02IMhcf6mHxu8Yfa1bRRvOZfbTFuBrLZwawZTv52vOB04zOjyRNBeb5RCel/pbah5GZKQJI+gO5JdX6iObOjIdOtGFvkllGTo8GPgsRFCoEAXqafBLm+5J20kNHT5uZl59tLybLOEzfKTipvm1f+oKBQXoxXVN41zuJcp49Pl9eLBXpEqfO8p4clyX4YWYNl5es2GHEnmbVXyKhgwlpj8xNp4anT7iU4zKXV+mpTbiaCHnaZOAXD0QaVQcxdkwjkDYMrdyP1mne3iK0fMuUMww2+WzXuW7ZT7RWGTrFAR91emdSppCU5VMD0HS8ZsxFGdqIQlYUn5XJWE6SYbQAUku1gp1ayD+kYrjPV0PWekpvcGSIw+IdiYmds8ov1+7pr7X9Dv8ccTv6CXZMqPlQiJ4BPiVYdZyYU2fQfvBQQovXSKhp9RkmcEyZ+dvG3lGjoGjBdgemMK58YgtJzcidruFAR/BuAeT/2+nTrq5sHcFtnElb4wYvFDmteV7Htcts5RurN87p+bNS9+azYvsIuJQNg7f+fmMklMyM2EKp6mzu8HEybm9BiBzerRasaUnx4F+qNKGHQKbTu63EMYo2HqP2zQXOrDZtAPc2cnpUTx8lURk/8PyE/q5MC5cMc="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-instance
      targetRevision: "*"
      helm:
        parameters:
          - name: "elasticsearch.resources.requests.memory"
            value: "12Gi"
          - name: "elasticsearch.resources.limits.memory"
            value: "12Gi"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-monitoring-config
      targetRevision: "*"
      helm:
        parameters:
          - name: "alertmanager.config"
            value: "AgBkEvN/TbGxyhJrUCjlnVbYzH4RQMBSmhKGdx2I7qKnIFIiRzna1uDRE8C+uZ4AQkelLiI15mbo2uWGmXid78ivNnBGqm1LcfJcvXNSUSitULq/6+hxr+gkyHe5EBVxnRRUwjnlfpMgA+DDGr7KAfjMslSF+TZgGEdTz8WCHV6/V6BXQXbb8HB74Kqdu26r7s9h51/+8qjEMrkuQpRCB+JuPRpWVfBSseRob5tm5OE1uMICDCHwphkGWT7yafiiPelyvsS7cZ63mLObvo06IraTVJ0h5kQQwU97ujHu/RwAYk1np5JlO2JtMDhgvyxhy/OSA8CUiARwhmJrQ65eczLabLvMrEXPKHCjlps1gTwwEAQjfJq/SyryxvcIGCvOXbIprn9FraE8xpvhIMnsy5kv5u2oLh5w39KyqEip1giR8rxF3l8tcjJ+snLipJoNNQAKoirBrqAhXe7PS4G5xjRhkQk3fWDKcfCIRuvfa7KvzRWJu9m77JyKYcH86J4NrpN7Gj0UI9fPKZd4cMQHjZJuZbncFNYcqPoaSI/XMl0XdKfl9y2GfXPdPjKDe4Jn5MKyvZv4+dmjbDdYl+qLkqMTbUHYMith8JQp2kGNwNKibe4G0MLYrxx5HCkpSyiMkk4t3UBZ7Tk+MBjeL1It2kHWT/BLXOYyC5p4knqquulZJjV/7vsvVgGU+RBrDEvJSwEI5w/sfmQMMfDXDh2920KzuIKsX56OjKFnG20pUCnVLDNcfIfFpUTBwe3yt5EbnE3rrRuV5NXlxj7RQf+j52qed3nSliW+TiRH5y/kb+ExQKi36Z+N5649R64iWbQTWELq81l2R/RooZrsQMFuX4oYd+ET2Orvy2p44g6vvlDTGWq/p9QzzSyN5tZRoHiAuWipD3F0NHCBa7uZpwejATBRHXreXghKVdNrgJzB+yn+wjaDWAKcVTC0U44LhimtweJ59AjJoekgrqvq9yD9tWM1Y7DOEQI0w/E3VEdvO/EwOBn2+bsbzM1o372nZrirviiPejIIj0/+q/ATn58V54/L5ejB/3Xn6ZdyGqnAHxVXUMa73H0kOAHXkmXKl7tJ5E6UjlwJdqNMw7LmhGJTJ9/6fv7nf+7soZJpqSyVziG/Xv1m6y7lj3pae3LcTCmwqnf3hyGPCI0/QiVqvIDpzydEIERm5xYgOr578K8pdkAP0c6ZNMQ4vfT4g2D3sMqMAoBl5E1nr++OJXG+cQyBRlKfBZmU/VW3z/xtF3FneRw17J9FoXa0EBVmDusT+KWxnurqMhDit5RlHYq0ZOJJcMqwmYUX//PrJC4Eo0m1O7bHeiy/prNLsui5c1PYulk7WfxHMdi3LHhAa5pN88DOxK9G6tPOr2cCMn9uAUaGSjegDcoNE5ixEHVuyneHB5XDVus1C79ZrnySUqoILMPPxLwxqkTTXTndfk1XjOzebFOv0FgM3AzUDWRWb9POGiK8rRgrN642Aea+mkggQHZk5podFqOCOXG8uI+5adI85DhtcJCPEeG6dPm35ztDV/SlDveDFyeIK+FbbsId50Rr/ftUzI8FIe1C6purTrISlzKMd8/59g8cvo4MIH6rq3G4xMDtsObrf7fLTUoAz+bnex8zkqrI7btmpMvpMef0QVxgPxVc5rzSSBruMc+EM7XnnoCTCd/VMC8zKi2CUsyGZ/8sOt2SmRNPIZpsa4pdXv14BXLXMi2GuFZVf5mPUl/Bj3ylibOT1Ike69UmR9gegoxL0/I6NRRG4HfteUqnsP4wdJ9YSqUmcJlA7VfxDz1nA9xvKRuZYyr3u1TIzuHJ0vxY/0Ir+lCZUUT/hHrPoyNV/Xia2LVt/Itt77N6wPvyrJsH7X21Hr/CxaEYXa9jeRrdU07B7g2DzcWDGOV+CIMv32G5rgV95GLId9sO3xjb6t27ODoOowYTFFs+2S+fhE7M4bgrYL0suOl3cMAXE4yGrcNncdEDpQawIYm5iBch6t15uX+JLhWUTw9VgRVjenmZrLB21fB86/cWBiHIv6n+YEb+swfB7cBT5n9cMpnyIXx5Vdc2b/Vc8f3k2GSH1AZsbLVP0npSArnH2t0N+ZpvaZRXF6Z6rMANFEPHGiPmqXthjZQv7gcu6PZprw11h8FyQ1dJ59WQHt2FDDnjs5Ij5lhRH0u5y1BJOhjy+UjjrIFQ70AwTGrnKsY30DRXVb1VRFvGaJ5l0AQMhHtg6hYxUNbhO+yJlewo1tWIBXjigUIQayKukfg4FBlU4WRreyt+KhY/S1+OpZFu3jXzQeSoRs1XSlkeM6pKt5osaWSlKQbAqDemBgyHgBSjQ33K93aDTX7+Eb/7+2oD9zw38lBvP5nsnKS3EgkfJXDJR2iwAg7L4WA7D68aWxx8F/WgQ+z/7aDOkhepvxRhPmnRIX8uHjYtHSEGLU+e+flR6wJsAoB3Pz9V43kH2a7ZoUw3PCIo8qZV48a5a2TgJBEYjz33DlUO1RWXihAHNlH4Rlct6pWauQoKGiUrrjJBLbH5Ti3ytF94FvKmHjRxX6NTZe+OH96NrriQoyH2jlfOBxTiYozXHmHy/Lwx8El3ujTPoD9JKYKiEAfARgT4Twgy6vtWf6+HXI2HpDQL1oI/98TL4kca28F7XJVJd/6r9KCbVDVk+hxx2rFYMPcFvrPbW+cPZbCY6XE95x7hHQmIQSq8CPmKMoy/KbIqXfN8syk475mX1ysnA3VH3sRo2fSwGNr2BhEbSgOHHbhksroT7YRtMCVsz4AJEauqRHWfemdXyuPbPY4RRGAyXYJ9OBXwrKbFLS4c26KXNRSkPyORzWNntRm3qXxKkHH/d1O/7DL1zUyOnzkipLhJnlMYJvuLNh1CTPfyAtlo6iITtVuOIf4fmBgknHXYZNkFVULFKhWX/QRJqrGlFyvAHSO1W+eqYx1P4SAXuZNe+YyOIR8UjXE3VCiCIHO5Ub58cGUOp4tBVPbmY22OTOf31E9dNAoZHIJPBoPyDK/emV4bhAJMRnWvyg2I9IJDaM1BvRMi7ruVkSrUdsPbKlakXuNtr/fIoau0ViddpQ5oxrNNL59gCd577XBJjH9mvCR2VNOpLZCExUtgKTa1xzFFE1X2Q4+1vLS2Mp7Wr3cXV5Y1tAfMZhfpoT4W25zvhnBjEhyG54mu7bBUoPt9fFgT6mXxT1c7vPTDNK4Ig8RbKHiL5Aa1KL1BLIhrtDsdHUySfOXeFrUw8+LyAI3EMkl8vJhPqTgblNujQ/DHEtzP48XsphVy7fWBGz4YPtL0pm2R8ranBgjsUrZVI0XyiBpnR/7LEb11ElKzualRnfzhA4S+oRp5lcmosdMI80ByoQR8Bj1T0yu64dBBk6qnWhKo34Q8C5o58hEWd7fG2fIUUD8bft5LyW5A8K5MVslUJrS/hNUWnEXQW8wyn4TOzbtibvYfIMXglY8cDn24OfICe9Gc94kW3RKsKhdbk1Z00BDK9B3rFzRPe0/zwFgNWC2zjbeVEDVd2/V48wlktL+IJqYsVyhwjc3C1ZHUAANMQwtEM5cS0Ku2mkPYmCJFN0iIp13/OngHYDLNGWdczjezP5YhoUbbm/dF6FE="
          - name: "infranodes.enabled"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-ocp-internal-registry
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      targetRevision: "*"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.play.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.play.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "play"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
        group: apik10.kasten.io
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cicd-tools
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.apps.play.gepaplexx.com"
          - name: "argo_workflows.server.ingress.hosts[0]"
            value: "workflows.apps.play.gepaplexx.com"
          - name: "argo_workflows.server.ingress.tls[0].hosts[0]"
            value: "workflows.apps.play.gepaplexx.com"
          - name: "argo_workflows.server.ingress.tls[0].secretName"
            value: "workflows.apps.play.gepaplexx.com-tls"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "sealedSecret.postgresql.password"
            value: "AgBJ7vWAsvjju5UoNEDyMi1+NHydrvYBbpswJ0metAPhaT2lrxtJiMWvSZR4+kWJWgYHSfRZQYfZIONubEC1a3FAF53K4hqUuaZeBL/YjlwZ3OVgQnFKyh5UIbSnDMC4+HR3YAE3k874su3q6Kch8rBrqgASjuu+A2hV5fEI/j/DjgdPxh4FxM9T2RyyoFikbX0AzAzsheuvqsoa9ETfgqfJn0v0Ju0n6bL4Wvo3hl0ujqV7FGZMlM8FWJ9nXcM5pPDwPp8/Gc9iFZc/Of2qhzU1yUOpaShyBw4nfNB9ZcD//9Lre0Z8q5fTdtCcyRvT4VL/myHO+4hRyNcFy9/Q6nXhFjC1itKppS57f0tPDdqY9d3QVScif+RpKRs3+6LDDJUJ152ymxClDkdx2n7TpxB+fn3XKh7f/IZnl/erXMmo8eJHLuCJGGXHVevzpPurjeF99LYW879RS/JJEKqKhjevVcmCMQSJt+Fm52JmpIdg8CLOziw8a5TV5An/g2Nqrv4FJBAPT2Wyfx3AtZV5gJBRwqKasnFECCR1ZK1ibvjc3RvkdqdIRke36fz8xkMgcIdX9Ruox7Fess38QLRnJoKpBvQHHfRaxB5r5A4qlUQ+HfLLDZ0JtO7M3A9TwNrkl0gSo/GVQ2l3YYMvs6IcCc7QQWg18uQQnY1nKOrMQd7En4xZRBOUKGSbyAKgEjeEVkIRcN+0vQ=="
          - name: "sealedSecret.postgresql.postgresPassword"
            value: "AgAhpIUHUN3TKWI5K2yIn7CyQvVejZQZLI7UgTNg1t0I9E9MWftRAX8TSUu3Hst2Rh+HPx3z0yE+GuDmKH2siWc6ZBAkNWMIZYDDDYUgLVGNNebh8LMBskmgqt6mGKv1/4x2JH+q+2cqmclNLQ4THGeZF+e9rdLWkDidVdy0O+FBG6TrR86YYGsb0/nBW0uYR/Kt0J1pUOwwuxgmtIG8wMpIbJgGv9heCdAONS8piIlb4eW1L4iaHPnbLqGszx+amTvqnTXi2YqlV1V4vAFuUE192edbZmXZ1mXLLn24rmANOHa3jzrpfHtYHDS/AgqYVKVYtip2ThKajkq9T3f/PlxwhmfVjEYBQcBu+I1zRR22MZ3rI2R2sV/zPQwWeqCya7o3H+AW0t9BiVSz9djvHhBVHgJ4V32CYO+qqfNadwq7zum3UK89oGdJTfiPJ51wZSBuabp//wWIiNsVoMs1paWpVnWoMKf0bosFpTKxB6uyJC35b3QBYzccuiviN272LDmAm0aj2EwdEo1nWWiZDsyDw+mTBPt84729hGV3sz+8g5x9k929+mK97H28zIdZzhHY0yVOLAer1jsKDygUUxZGcPxOua6zXpqP3DTESvNtkrnaBFJxbeR1HhYRMl2HE1SP5GEEIfHXB5D0XxN4NekD28x57jRecsfLvd/YHKVzzfdTld0Ae8EjXm3FtEe3K2l0X90big=="
          - name: "sealedSecret.postgresql.username"
            value: "AgANzRJhzo5xONwx25DOddtUToH8sS4BjAwE6AFB4opKtKSv+eJMgh61p2ABGY7Ivtqt0CzWiFg+51Q60QaJ8t/vVBwwImPA/TVfmhBnLnnmuV/jSG1VfvjrfYSoPfKtXhJTiSjsmZcqEzt4XKiRVB6eCCZQ8wOHp7Q6BDz/2Vg/q0kU/7O9KM79c2356DboKzDhOwjk4NEItOiqXxGNCiQ7gWb42KEaHUbqXhxIGVpTgt8HBaP8eZ5C6oPTfi+bOnhG4U1WP21UQn467GMDOATeunzNMNImKS7flW+A/qlTVMQugoMz9NEtUdDIUAEKMpgXF2ibMDQMqVkKFjnyt+FX5KNYfpGSIimy+32Anb09oIfIgpQknNn15dFLqkANZWw7YFBTCe6Q1eG4EkKfvTVjG09He56AMOn/t+2oVv1h7eOcra1i2mUvCI2ZIoGmaqI/nDb8XXtGu9rwR6cNs42ilogJ6pl86lcdzx1H/Ju+C67m7UB/MWEYtkrOxE4UQRmTo82hrBqPpunCo1hBiPVGY5SZKfwis1UJLTb6NvSFZHqx6Tm6Ln5jK/WCAOosmphGWHydehSgwpnKb39b4LU7bc9uJl3CGCIpgnkUsHNvznwrdCxSC+WbPxpDNNrfbziy+xL9wfd/nJRYUSmORCYvcejFZh1R6xkXEdY5UoS5Z3oF2iwJwD/4lFYBDQkP1YGWMqeJOnjzrA=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/play/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true