project:
  create: false
  name: gepaplexx

applications:
####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-updater
      targetRevision: "*"
      helm:
        parameters:
          - name: "clustername"
            value: "play"
          - name: "consoleUrl"
            value: "console.apps.play.gepaplexx.com"
          - name: "slack.channel"
            value: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxRk0zQUNES04vQjAxUTI0NkI1TksvMUFIaHlIUlVsOVlVS2c2WHp5UGh2Z3dDCg=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-instance
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-monitoring-config
      targetRevision: "*"
      helm:
        parameters:
        - name: "alertmanager.config"
          value: "AgARCl+MTf0TBxvYrwEMPF336NJMysmHOcsZNyP++j2FbkYzEIzsIEyYghGQlMp9vruT4qi2Rlt+ygZtN9nnrkH35s3sI+RlsOuGZfzr6rwTSw/7LsB/HV1Zs1DmKskGnWobLAL2N4WTlbqAg+Om19EE34GShodhaKIjnvi9ZB3sOLvey3ch1bNOFpTU9DGGIcc/dWe3hnGK6yV/LJ139jETT1WjpfAbVbJPDpWQCdQHo2hUggQY8sOrM+6On/bK9iRJ/MygXNnBo2cdDGG+5al+3bXs71knqP8Awb+0EM2fbzpy0fsG2GN+CSnPUQpC9eMV5qEzbYt/GNlPl+oNbATD7eVcZCXSzPpwt9UlBtPxxuKfviaWZotVN5fYtfd3/VXI5BS2zdJmPlxfLnIFX6Ti91IleOpoAbAqayFlSafLFGoIQS/c4awcLugAs4Xg1emW16NcRPR6dELmY80HkLyPSG9V0PTUtkKhJrq/C+6SdTsJ4Xs4GKQsAGYLvdC9sFVicm7UAD4r54GgWZHFVG1T5qh7XXVz2CwGqlx2VzQ79SYyGhV6CiWRLXBzc21SyVGPRXm4w+5n4yzCFTuHipoTXoTkzjYHU3Yyf86fGArw98bVxYn84s1nnBX+RS/227d7xmv8jypxcEB+qCkGLD1lJ+oYAl1+dUP91hIBkok+UMAfsFZULEP8PPBvkKFb4fyU64EWc2itqdjMrOHEzvwDu2H/wMSz6ocLGRp1L6J/ZB72vRJci3hvNYxH8tIs7JB40Jm+8GfVYTcHYBZ3VXAbumzKHlA+i808Pf2fO3bzAIrlcXubhYR/ya6Vt0dbY8Bd4nOdYeZ+u4NDKDxx8qS7MnyxsysELJUXDgL4fH6A3L+bBLY03laCyzlSww3Vs6CXgcE0CA0QjMfTuBOSc1fXqjgmXW2i+yOUh4pqlIVP6iFZor1frZOl2Y0wTkdZwGziVhONZFxS5lqmggApaoVbHYwN9XGvqHJOBBrvPGhH1NhRqcv+/Vl7fwNgoWpoGkDPoCQajA9i9MjXB9RqQTqG83w73eyHTicANEoKApm7+/3nWlz65BxmdJe0//qZu8wSWh4PAYMQ9HBXBmzM+Y1gjLCX6pXDmP0+Ql5fO5GikXDjVv9VxFBwHpLctc2806ZOZzqiOH/hUjK0kzDXtb+ZhSz/xvLPISlunfow7Jbs67W3UWhnggQtOU3G9MDsYQ3XwE05+Tne095Pb0UvJWtmVEiIKiQqQQTsZ2uxbMC2i+ojkn8nuqkl6CPv/XfWqWlnCaK2a9tHFaKC+eG29eBir7CbUj8el8M+lp8mxwLr7gvblIfBI7moaltAL/+1LcP42lV6VBx4dj8QmXCuDoKBYPt2TyfWRq5wmGiOjyYrM3F0t7XPexXasWeVRshmd2QTbqQCDkSlmT1q1V8/6YWTRk44iC7clK/exqPL5RdDrh6r297mVeTu9787rnfWlgrGur+clr66JRo9gEC3+smTl3VtOBNX3l5gphXT63rQP0RkqHUC0M1yIIcW4npP7w5/hZDOoVP3RmzKkCqg5z/kK5H+JopJr6Jh9yGlqXXvbMfPF7r9S8rVX6SNVwC0raVWIDUhaLUI6DyRaMenb9EbT60b1MKJveqapAxkEcCJsA48Nmvg5l5QZv+QY+mZpBNhNq/Z3Q9rQuJrEKsCWsGXnxqNr1yQUq9tsOpVK8WtT8h3fKEinI3LE4kKlausp1mkrTPkKe1nne9lyO9WBXuupWSMkK7M0ZEYQOWL3/vGyDBMaCWQd/72q/U1+u0ESoAg8qx2CV26b+y8S5aqU8pEMCoGk10UmS87mw3EA5HLq3/r69hQaqEyUpiQIUKNkzUPH9953vTpFPfhoUksCbbgu9pxTGM7rH4cei4cBfr20p3kavR/4J8fPZ+Csge3yuGWx4Ner3LJasTE2I2Di3mWCmzqFQET+NyRC8UBRoysXzlOek6o4Uxp3XE87Wpd/kWBDhakur5u7uCDEYMYvRu0O44tBofFQygzX2NXwUaNp0az9qXI0wBtjpF8EQ0t/sJHfkwJesecxnZF06xa0shcqwx8XlOmfelHg5sQ5qkFN1rasFiwQgazzpnBL0dBKkNozB/V4x5mfb08XypjIcHyed/3DxQkg9hwXJ4pvzMtpziLn9aBWZU9gWLHv2twN9lFZldpdXpcvtWs9PKRFXGpZaCziq2tl4pKDy8OEmNJ9E0bmn9t1GdiwjMsLpd+sctc+RmW2clQqVHwu1cDIiUXQWETrtYtFjiClKooMCvT/L1jY3L19ZoIttBAoWhrbO17p1FB+9UWuOOZZAloCCt3pVD76SIuS+uflXk4aZcIRG4b4ohj8l5+W3WPdPBU5p7fhhFAtS0aNxl1NmqQHBq/xzPtf5RWFuu8+kBknpSCF81TaRxZKCMR0ZNU+JTZV4W82jZHW+O6KDDR2KFlauPrPI8iLxsDWnHiskfE29pcU7+tMe8gFsRsMxhimtpVGB4NilkJ3fBRYYYjoXrUcbDYKTMGElef2LTs+/8zoyFAHTtUPe1Sle3hi/AnsLvteck6PBY8dF9GDngs178134hYbbSKgI9Vq/wj4/m17c7Lw3ABsrFAMMRnE/Id/CB+k1gOIKOFfxJXvGyLxn6H563tiiRa1kMJK/dqfeLtdDBA0dzY88RZUihGmDz0VlO7IJ0Rssb+tEfWZ6zpOF7oPQiPJuTsREkSOiSlfd0PckR8yUaR74htJNKN3CAF1kaN3MfQ+TvWdZgQOcTMHOsB7D0YJYrHkh5tlUSYWHB8Eg=="
        - name: "infranodes.enabled"
          value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-ocp-internal-registry
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.play.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.play.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "play"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cicd-tools
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.play.apps.gepaplexx.com"
          - name: "argo_workflows.ingress.hostname"
            value: "workflows.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.play.apps.gepaplexx.com"
          - name: "sealedSecrets.postgresql.password"
            value: "AgC4F31nAvIOfADdFrAOJoaWGCGWrsmhC44qav9gapQL+dG5ug43jrzAd7huwhaL6cbMcmCfvfXDFmI+PFI3+KlziyQaj4JtcijXl5OvWfebKVbwGSwU3pXi110V2Z58TVBsvLYnDivPAhWL4l6+lxl+zLt9a3OB15HfS+x1qYxhx27/jRGA3Cidfa0RVs1bDwLdtemqRMpi1XX/jiqRzmhcdnfHf3XDsrCjZ3Y5X9tPEPUGJo8HdH7my4nopHYeVjUIStB80MsR4FDjx6IJx6uklKk/cP6bncm8thJxiahN4hjOSX3Cm74blW1VqtClRL7382wIIqhR13bmqqGBQKpPvAIYIQUhfV+BIFHbs7kUu0nY6ESVfipwgZSpYI9qlPvduEyp9QcavqcdMflkIIZUxioVN9ToK0aXZlMrROvjeJbmJkzRTMj1I2QiDI2GcH3MRdLPs6WkskYl5XqXYU0d5uMTyL+P/2FtHkw2a1ASXT1uEZ9I/aR+tfpr/fteUte4Odlz8B9Z8yYOFCrkeBVzEYHdriF1NBnD4cnRN28LVeeggMav9dlsbQnn2a+FsnKalieH5Hw+CT1m6aDrPGBiZ2rNa7Ld8OllW3kqeXubq6rJswE9sUhygaWTkICb/m57K+fOZhoyZZHHoqN9jeJTwpof4DXRbvXtyqe2I/bw7ddbpakSidSzTp6kfE8vgt0="
          - name: "sealedSecrets.postgresql.postgresPassword"
            value: "AgBi6e5J3q9HZ3zbt4uf3WsKrlFOtlu8oE/2WXyez0JPefPf4Cnrr1yI8JRackRc6gVE5/jGQzcVWzv8QVqs/GcUAkw7O8iI0rygxz/36uRzYlx4VfbPTpcESTyL6yzccIXCnk3zApM8AEz7QEdPTGQTqR3vpm6kD75r+sippzGZ6G4pMyPD/aTj6t3wO3vtuGJM8FDbHZx2K6x2bpv37qSERjZabkpiqgkaR7zTy/NYLB60XwP0YDelaLc824PA1wUj4WKy7MusOWHR+9PEsHsHEnTleFYUP0XhtNO2s9bnZtcW9b7Bkp2OkTJjGkUK2B6z9h0GAq7SpXCHHD7diezNNq9mYDaLGqea63DwpwyGoFpAZI/dCzhg6/aHp8qAPmW9tqpUqErmA7ZnUOIV9AKkFdyJmImDpf3c/vj9eieryb/bbCc4XGbdeKP+mfr5n0iUn5hmE3ZrD9K3O66ZZMZnwCHjb7vA1BUO/6lM6Lm9eutC2GAjSd44RBY/pe8NTbdoByl3lf/+W0xGGFnRul+Ee2Fvjm7bGb1J0rSPtZ8Bi6NA2Z/ZydwgoCYc78USOxQ/ZB44e9fCDoLIHvqg3oYYaY0ESHLK1p84Xr6nC9Hc1prGauHjYbCGNytNW0KsQ/1dopvhkFqglwLHYMKRthcI3bQpbTIuA/aGynCehmC9zDhJKZswcAJVbpjoi8/bcVQ="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  ##################### GEPAPLEXX-CICD-EVENTS ######################
  gepaplexx-cicd-argo-events:
    name: gp-cicd-argo-events
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cicd-argo-events
      targetRevision: "*"
      helm:
        skipCrds: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/play/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true