project:
  create: false
  name: gepaplexx

applications:
  ####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-update-checker
      targetRevision: "1.2.1"
      helm:
        parameters:
          - name: "clustername"
            value: "steppe"
          - name: "consoleUrl"
            value: "console.apps.steppe.gepaplexx.com"
          - name: "slack.channel"
            value: "AgBIPG9Zo8SxwkZbayJT7kKCFT8EETzn6qmwPLmV3H9KOgxUWsPdhKQZC0Qnkc6dGJk7jv/rDhnzzYJ62hSvIvgKh5FQQkOyIbAvWhIUeO7xSWQK38UhULmlIdnhMoo1NVbmdWCM/VyF8N4HizqeD2c6UnTmJuwbWR7vGFzxD622G+arsZ4Kx5mBGnfcNsDcSu2yiq3R47m3iB+KNgr3M9aJFAsQaWHiiufgFTTqJicNAfo3FjzrPPvOd57B/SZuL0QXOlxUMVzHA/RGn5/2J+LWjnbOXH4d3d6zwmgv0mLAor86hn301y3ZLVXqUaphaMsPuVv8/KEEpTYu1uyw10cCMSr8wlCa53O7RdgA3IGdjHi0y9qZxs+HFzuRVhWOPmcADN3iUiJV7FZtW0C2N7HfdO3V1365D2BXuT23b4OzGplm2oj02XKeNAN9cj2/oWTVx4tSyojr9L/5tnwHlN+Sg21ACiqhRoAmQRe4K6YO+YSDne6+hE3aDPGAdNQQHUSHe8JHhaxzS9DiHj/R/5waLaSrm9TWlT2t1gDqehAN1aPra/QI+ETJtVAA+eapv5PUq7sWRyjTdEBMEOLbClIwRcHQKj/fslNhYEv0ZLAN0JeyBJwmsXtth89m5wVDPz+0WIeH2JbkBr3xLcYXR4OY7No+YA/jdtCDntyXH4GmnLIW55z7fE0MmbxtniT2ryHiiM4vrRhPC90nNJykMaxrBP9+Kc4HP10Gbnf7yGlXfuDzP1sWPpDtImPTe8GMpdGqXntLlnS0FXOGeMVNIoFfqxT5GGlNmZN5xuaWwqNhrIo="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-instance
      targetRevision: "1.3.0"
      helm:
        parameters:
          - name: "elasticsearch.resources.requests.memory"
            value: "10Gi" # FIXME
          - name: "elasticsearch.resources.limits.memory"
            value: "10Gi" # FIXME
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "0.1.1"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-monitoring-config
      targetRevision: "1.2.5"
      helm:
        parameters:
          - name: "alertmanager.config"
            value: "AgAyQdb0X/sOZdbz45bc/iovKz2VBQaoHRWq3wS9u2MHltq7lL0T9hyf1qbq5Dly3Ej2XQDf4Er/jps2T417eWTjn+F7YCTsODRRf4/Si/nLCks8WNAaqV6m/13i7IXVr0YJDB8mZ+o+3XRQjcYphzvvXoyXzZmwiMdQpHV075rJq1QL6pIiUDcdHCKhelxjomIAJmDXG26xO7dTsFFQb2ZqBHmXqnbLywRP6965PfJ4bn0uZ2qOB2c7H0JPU3qK2QsGBwHZ9GfJRQOf+pImdvVCTYoGJxeBls1jSs5qlCN5bb7bDOkqifTDvYzggF/aP8VdcdWebmzlonb7PA+PuL0BlzRHgKpTAos+k+a4C8a8xOpO4HAti4R0Yp/kPz/HD4nm/zWJAESnRSwAdTZ8e8f7MgToTNhgN1wKVSD3qfVTrsnMSEt9OsZvUuUY3I1QFPwgyC0TlUD5xnVKAH2tlKuq8Fxf1S0tP/keHqR7fX2aLnGSRMtzqBo0LlKvzwqmSPRC6yEioYTTnPz9wXcBWyHzrjF0hCLEZrwVgiwOVG1BuhgECeMxaQUf5ERmx1K5I5AVPVPTuGx+KPKfjUb4XVQdJvCJsl6a88qx7ze24uXFh5O+Ie33NmbQDC2qMoTq+eX0qii2/Z+6Y2mXLZjPY60RRFqhXiHiHNU4n5OosMPXPgjIAcaa0CYPWL/l+zBy5YwPMMf0bicH7/+k+a1D9fQ2tPGOh+kON3QY4+iWBf8TYSHigaMrLWorPMe+vBmVVioEcQSmFGzsbb0nupk5mkPwy9SWW1ic24shkFF67Vtn7YteKYjPaFmdEDZNy6KXAXld5CxwkNhUzI0eZ7nqxvAachpv0sbE03wcaMVoEntYw+6LccYnoZpuxU7cZNTYL1gBUK+05Qtw/jss1KJVOCiLBGM1EUf7L5tWmNMXJXmIQJ7hg4ODxNyHNpPQk/qjHLUGnBBFvvYEcyq455uCyOe6/YFqvhpQ2Y8MJRbCHT2nFNo2u7ZqZuIHLkvBBwGpHcz+YZdp8iI2FZRBQBYtUdtSRlWcnjItth5HyJC93MhFcj4VYgH6Na/NvkYgiRoDzjDO0/jdjixIaF7ty4s2KNO8NOZ7LBHUtZ06FxSOXdLY3j7C5Os/pYofDpOMVzRcvDXBJgS+VysMqINf5dvsHy4TpVf4QexEO8F7DZFI93KRJ83Gi05oPFKfWyw1+0s81UAw6OW3ORDJausSpg9YLLUtL1npoYTwMutZHWty1XB6DXar8XzK2M9aaWX/MoYnJgoPrCtwYlqWdZ7sua59vj88tZCcOu6WCskItjH//e02J005rsvWyIdQKGOzaJB2YGb2AcYrKJm6ssPnFkwHAv9QdEhr8ZW+hR6YM/ZLBBDPWHO5ikgagl0vFnj25C1u/IC5+efQigXI8Aa1GAhxrM6/T20sJ7i3B1dSO2AIjaOjEUkF+7ljOdNFXlFOqpqii8PRk3fGrxMYZnSjTLKlMTh6FYlpYtEgilFWCCto/bapQW24aBoja6dcy/THPPsn13sXbvshcd7iPjw1bG7RX7rf+pZo5mgz4++2Hc5/JV2cgi9J06L9n19dV0hkQxQ+aghGzTxtgjY4DrreEf+UMAenQcrvqz/b+mFHVKx5UX/4fnfeHO+pfsQ4Ixr5sGbcUibBgHDDNRkAJvCkberNwDSHiRbpeBV1xkhfP1ohNkLdH1/+dE189KJj7QuFProB7WZYaIZG1MrVLbewpPPEjog7Ens/wVwKW217GGvIF0voqte9mbe4MKyev+bcuiUNQaHD0jBHXN3qdDM51LNmlfX9kggXxkYpeLuf0PTAO3Eek6PqBXAQrtONgwS8Iq6kmlgYQ0WleZDSUWpL9Zl+wfNr6g2fITyVTEpSs1sX0sSIxzXNE6BmhxieATc49GKszRcRXfeEl6NhZrQUhN/6E2aWYKCpR2TIcUMTrS5NXogv1gimS9T8aHsrmqUNmQD3+y73NW8j04gb+AKqx9RnJ6iGo3Shs72mYcuWTJne7iFCleohq47FIOCtQrWJnhunlkyS7rm8KXStTf17LM+agwOBzfH/RwtbkaVJiCl8FEZaVnzKkLt8J9t99hgbPafqc5csHSZQM7/yhHE9pNApxKyUWKrEQRF9xAWro6cb5Dj0GYrhwIprhIh5t7hJntCVRdbIfIzH1l3Oq3ckbLiO0axpNOUWTLu4LK3BBWOt8RO/8v+GYMGvm2N7ef7alqwPAPO6TEiKXR/rgZ0BzF3k/Ek4my/SnhilK4hbY+Vc26zkTOoYHI476AfA26vAqoObHAo+/hJ9BzFJX6QwKRLuZwuplyx4PYY4h5BruVPvdcjLu0DwgqKUgVHJSc7pffKjvKDMtS5+cVxqigrSS8HvTeZ0jaZYTFxX07aS/7c7MRdKJtb9OuKt2JmDXWwAY+V6CossvHqIEnP3Yc+C3c84qSAKBunTOohaURIcB72e6WCe768om0qRIpOaa43Rg6CjVKqr1uUU82I5VykILvCap/qVtBJp6mcnwYq/UIcRaEhewgQpTQj8QLPMRCqjREz1NdZHTTZTfmDAcVeFBE+U0C3OUyP/uqqsOyjDaEISTE9pFDathNDuC/vF5R30hAE6WilOCmHMXJMk5/OfbDO99ZvGiyeItL1f/XsF3S2K1Y+Pux9GLQ+SJZP9bd6g01T/Z7VfG6ffqqhPhE0tVVqgATQVuW3kaNS/0zS6m//9vNsRAhvIJnuefru8Xph9tTbfLZhtbdiFydZZ+4L793pyCcPBShtiNinoVNDqDybFDIyrFSZ22LH5apENyZpfn2He6wUwqbByQrNFknTffSI3/4XZ3dW8EwbMcEUgClYbn0QFislNYxvX42pSREW9SbO5C/ra0/F8pbjax3q5/gIEvizLm53hA3XlGrXSlDIiO8kau06CDPPem4ZEuu04425YN188HRpM6ul3t9n4VUaTtSfTsxEBl8QjLijHxDGSUnxGiL0tsrzPQJMB7G7kbyGXLINRCWuSbbM9wk8GDNDom8WMBsLvmGyqEVFE2UBGHOzIdV5LTJLa2uhYmfMWgvAPPcpB5YWfdymteANVaLrfGahfYcd54nqPjmIfS4mc9aB5Hi3Sg7rYyQjNKOOq0ai+TGSOJdPp8gCBjjkh2fcbMwbIPnNu7o0ezaQBJdihJX5sZde/R5ZOJgejqx+Go/FJDxW+e3HZMToyTHxISyvPV/p01V96LHjyRPdrlTnvsHRzMT5+OvuL6J5cxnb9E8QBvff0osNkrZNGGZIF1QKxKCcWYhTlBKera8bDeXKJmikzTMu96BLbFvBH7NHyWTTeJiym35ZCAaEkpKOedISghHCw1a5EzYnXIekU0x56i2YrwYVJv2nO1NlfOEcl4/avnRlKM3gCOckNXpYbBZ7uUB1CJNJVDyzbQHfA3Fhoz9SUCUu/8C3aloBUptVY8OrciEFQ8VvCt2mpybS6uS6dp0wZvcwC37rNSRdkghefCL/G5Obu9s4v9TD3xEoIMliYLbzvghhGI1/BeAD7mFkdDFQUeoifXGKbf4wy12ECSKlJs+rh"
          - name: "infranodes.enabled"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-ocp-internal-registry
      targetRevision: "1.1.1"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      targetRevision: "0.0.5"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.steppe.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.steppe.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "steppe"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
        group: apik10.kasten.io
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cicd-tools
      targetRevision: "0.3.6"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.apps.steppe.gepaplexx.com"
          - name: "argo_workflows.server.ingress.hosts[0]"
            value: "workflows.apps.steppe.gepaplexx.com"
          - name: "argo_workflows.server.ingress.tls[0].hosts[0]"
            value: "workflows.apps.steppe.gepaplexx.com"
          - name: "argo_workflows.server.ingress.tls[0].secretName"
            value: "workflows.apps.steppe.gepaplexx.com-tls"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "sealedSecret.postgresql.password"
            value: "AgCGbpeVyrgLYUX0KVt6cvcqFc25mxHoAjMrAumZatE1RRliej/ucAY2R4qh/p5kZ3Ml9MTh+krLauB+OFZT2WX3fQ+41JsgkBbRCEun79IGVE+fuD7NGm+RCKTnXGryGDvKLHgNRaqMA9+I/cBPXxdP2PxblX2rq72H25yGs9PxKwUJEHz8g1hHVw4V0o7qwI5CTWAIu5uFxyM0VHAhfFXiWrRaJGWFKEtXIgB+3WvufayyyJ9iG+vIvNIHb5cKdAQTCtXXNVbx+Rkvsokx5XB344B9VSm/QKqngVm3cIt4FwUQGqaxSfywJ7pblSprP14cSwrQRxyP4MxRhDfroLGBnlV5Ete8yoRF7X+F1f+29/E4H0uAozh70IYJ8/i0AtdsjkDUtJTqKZDf/l8HORmojTt6WwnKM8P2oJnmjonhaB/eiH5a/p0GCWlnJP5wHsFls7xbEW4TLXn1D5lj4HnQJ3e3tK3rTltuHkx7deYgx0PtWKCT05NrIZm8LxnGUjSe/dDpGYiK4UojpCfJHbDN3jWS0VJNxJsOXRn7RR3k6Wb7y0AqaccSdP+bTxr4vmACTjyjinLd31Bb+J4upp0ICUF/F4pnLyMo0COMFqHe5IzcDdOQ1j22KKx84ojg8+mcNgaypprdgHJmsQKco0jG/D689KDbD69sY8V+/FadIkI5DX1UwAqbPnaB7OIZzGzDX2EOFkrE2QNF"
          - name: "sealedSecret.postgresql.postgresPassword"
            value: "AgBPIgrmll1AnwoTdhUcU7/b+5ONkPDQdxIVlY4XSQQhP2cgySQxmQRVtCJ4iL7GmtSaoFn0o85RlnScSA31THd+p3MF/dPChtLkvzCXs+4juwc0bqXAdQhsVf5hTtrQ55lEdFOZZXcLWEyVBAIEgF31qPcZln+hvZbC/GxwNjB7CiavGQ1Kwe2OyLa/tZw2FEkKqlr0iJi151EuCFFwIk7K+zo+xYnW9RGPBMjcUOw04YJdgfE98fmKSuu1XnmvCtjLj5aOXLj7SaMU7K5yR7klgKeVlFddBVGumgO9aXEwobEc6v+bq5y3Q7CEu0IUIlwplmFTxh7z9NlkVvmBGyaZftBuitkBPWFtKubDwfSNnhaHjwviNstJEAawDLRPSegNawA+4+GJQ3Xh7ieL87IP3KPFKYidx1WdkfmqDQ8u9bCDqKNLycQSTc5EHqBljKH5+ierFPQ1dDYphi473v1uIe6B6kChVLQ4otT/3yPduCqXzYFWvF0ySGET0sh9GxJcR1886aUo/5yzeFwUNOQT2PBG71rnXfbv9YbF4pszzg8Zawh+Eond93ZO8KmvKSC2JK5cMMR1fs8SDuHNmoiuTz+UlZ2XWlGuY/lBr2V4TEyemhjsmvUvIFe/bIeldTwYvMkgH6iOIsu0TQvZJ5vFk4vuLSDdfw/u20QXJP6HibQCkOJWV+3cpXEASDYvxlh/9+figDTJf0LC"
          - name: "sealedSecret.postgresql.username"
            value: "AgBTH4zhm6Y0Pl5ZUr7ZPhLDzM3uJN/zA+bxoMn/rTgmsf6EQ+NPG87jgpqBUMZ6K4Iw9S6TiG+1syWs1T5IX1i+DAVNpskZojT1JfkeQPCaA/D7PxnNQD8Cfn3khtya6Xu4X+fh8ZCSeFN8ISolhRJIxj2naTvVv2Vm2St8yZzFQncB8/kL2weFN9ku/jZOBEqhlBpovaFh/zOh5N8thtRTTVu9b6iWCkT5C4A0Mv6Okbr6EA5hYRCtmrsOUpBSuzGfeIYSIGdhgVMJydSm12MlHbwkyGO6gsIGLTMR1RwH6qDskRNwssq8ZBhotobAIMclVP/Gpq76IZr2qQnDurQAIaZCLBL5zaqoIEM04HesWaL3gNYx+IuEMxzwI9ym0XjhUXSyeRTf/ldKjasNpoqXgOYlkq2nEKFG+R1fcC7c+S6Q1lf6Lk1eOh7J/5ZD55S2YJwnq/EAVmXn0dLCdp287a5xCgesAPuKbPZSPJG90688XPpMJo7Xdn+NdF9aeGaycbLUriraWzBkmRy3MvW0JHQU6mUiYNINuuS8Ak55clQCJ4Bl7L02uZpIfEo6bdZgF/pct0NV+fYSPbZp3wKQ+6pRVk0bt9iwegiCHWtQMBx3CLFULCN8WfZCqCSBcJZ+Q0LSza/7AEoMolMfkXkv0J3uS8eFV1Q/q0M5jtB9vGNBk0ynljlMJ66txhaiaCa0aGFw1y+qwA=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "0.1.1"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/steppe/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true