project:
  create: false
  name: gepaplexx

applications:
  ####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-update-checker
      targetRevision: "*"
      helm:
        parameters:
          - name: "clustername"
            value: "play"
          - name: "consoleUrl"
            value: "console.apps.play.gepaplexx.com"
          - name: "slack.channel"
            value: "AgA0ym5EyLQjaqkepc0IEYUruXnlAorIZocs6od7bs2pvEh0Mo9Ij+QITnjan3ImMxHVM9S5Le7PK3hsXIJTYibsJy1CRfahO1STCFhlpqXyhvkjpm9HC2q7vI3+CnoTWT8L8RbHFg9BTEYh7hfh9MBfy1W8yRFy4oq16K9V0HQB9ah+jkN02IMhcf6mHxu8Yfa1bRRvOZfbTFuBrLZwawZTv52vOB04zOjyRNBeb5RCel/pbah5GZKQJI+gO5JdX6iObOjIdOtGFvkllGTo8GPgsRFCoEAXqafBLm+5J20kNHT5uZl59tLybLOEzfKTipvm1f+oKBQXoxXVN41zuJcp49Pl9eLBXpEqfO8p4clyX4YWYNl5es2GHEnmbVXyKhgwlpj8xNp4anT7iU4zKXV+mpTbiaCHnaZOAXD0QaVQcxdkwjkDYMrdyP1mne3iK0fMuUMww2+WzXuW7ZT7RWGTrFAR91emdSppCU5VMD0HS8ZsxFGdqIQlYUn5XJWE6SYbQAUku1gp1ayD+kYrjPV0PWekpvcGSIw+IdiYmds8ov1+7pr7X9Dv8ccTv6CXZMqPlQiJ4BPiVYdZyYU2fQfvBQQovXSKhp9RkmcEyZ+dvG3lGjoGjBdgemMK58YgtJzcidruFAR/BuAeT/2+nTrq5sHcFtnElb4wYvFDmteV7Htcts5RurN87p+bNS9+azYvsIuJQNg7f+fmMklMyM2EKp6mzu8HEybm9BiBzerRasaUnx4F+qNKGHQKbTu63EMYo2HqP2zQXOrDZtAPc2cnpUTx8lURk/8PyE/q5MC5cMc="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-instance
      targetRevision: "*"
      helm:
        parameters:
          - name: "elasticsearch.resources.requests.memory"
            value: "12Gi"
          - name: "elasticsearch.resources.limits.memory"
            value: "12Gi"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-monitoring-config
      targetRevision: "*"
      helm:
        parameters:
          - name: "alertmanager.config"
            value: "AgAlU75U8LjmTRyICaZKvffVw+JRuXxfGw6TBX4Bxf2iKF4xecKefFHMRAFMrybhofNw+bmcxNJN/+fWkWivLjkx2XiKGx2sxwJL4Y820cDNMxtvDh/rpy1UjL4sMBvGzTWG5uDT7inSOKPm4bXt4socsk1QbQA3pQVDYOXsCtHMrr9IDskjw+1yetBlGHCbZPmZ+CcM+1IgT+8YXvxeyyjBTCf5zJ4nc79phUOQpBDYWwcw78tN4Z7CY4noxCUV/hqg5f8FxbNUXFgN0PNc3t6vgyHKDrNKI9Oryw9vEbxgc237dYKLsZNaBkKrG39ipvvYGOB7XuR51ArFk1Pa0AwKqXzctIzhsHW37OHgMvfcHmsYUKvS0Af0F42EbYbzB+OJQAfHfYXoSRF2Ql+iaBI0JFMGzN65FnbZrUDInnB1R33CnByH1xfyDXV1GOBb6UoeSiqD71dWZuySgK29YKiKkbhW/4L60Q1cn7jFWY7dFNu5pLsRT5nWA94sVYpvqiFN6y6UIb27E0+no16jX4fWwsHyKYu4X2XIkydeg5hmmtCz+5MyrEGdt9xFqN6KKMvGXO6R3+ojBO7kFKNyjR+StWtm7vQ5LfnysJzZEtRUEljj/yVeA+9XcqO9gyE64Lc8bd6ExM1KrNIjFxeIBAsCDZVn5bAoHuQXiIu1Kxevog2G0W2CFBOtTv2403hCJXvfQEaDFa2XbQSdH6yGiHoeLcsAalfnmLUjjNzyshghep6go/WEd1umAp5FCUnOncXliIxGD4YygJtI3nse2P9DttBAWc0sqDaE6W9G1XVmhYbjIQjk8i3bgh9YARbQZeeSY7eSKs1uRLhsttTIz3nh3zi5wXiMIVNt5wzp60BKxnIHGK2fzYKUMfxhx56q9dhoofC9sIWMDEOaviSehh2R8ggAI+NhzLqabKc6mjcG6Uw5xWKgiWSM2UnFx5xssffIUm0spyM38zl2+eh733NaJb8ZFQr33MBVWWGsGtlXTzhiNyaX+dFAQBtENnv0R49ODnU+NBwb0e4720Y+NcDBbue4kZHXpn5WkjmaHRn+j5FafFar8n3ijMUIRZzbejeCzneoRW9HBv41YEu8xx38x1j/lPP8wyaOGTjf4owLHAnBf4iC/rQhKPm1Pjyh1OGMxLqxtQDPeuB+giWT5HtvrSQVDODXNcm/fMYu3AQyOeMC+m2lCmrYj1DROgP4Rs8IKMHKOJGEVU5sTMD8D9pnpiONBnUPnpi9ZYJCm7uPtY5uO+B3X4HaRNX31dacI7HX28asYzf+iYM1ghH3A42+n7kLQUkZRc1MAiZVjxEnwIno1b+crdwAKExAV7E2MmZDdlDtVDxzZweZTQWEE0Uh0OhGJmqx8NqraSzN803v3Po/FXESI1vz9k+38+USTVWtR3cUwBbuF6Sxz9Y243WzGOGzUexR8mZyJDB+1m4rFlFvRg01uHBVKdB3XGdsryegKSCB5idL2pGNmtsRyMRaRP8x3RVHwYOrm/8wQ6vxzG3Lf2bUVkMua/NB6h9ZNjTWlEXaBKU+xQ6uXL4JFr/TeRYJOMnEVXjhrO0LC0N/klIuNI9id58STQy+WQaF2gp8YM4x5RU7659vB3xPb5v5Fc2uTC97DbhAEKDnqECL40Di2pmLbb/LnoRGzmQNovwF4WFBOghWExQFYX4o2K67NOnuN96VQm0AcgoovjxnuZMJTzP34Opf6Yw6s3cwzBtRr14Vu/SD6XrQbcIaFZmsMaO7eHEBPr+SF8kWCYNuWigqmeLpctmGg+fzH6wudPaM7X8soRTfd99TfjBvdfpXpOPoObpDB5lQk1D4SsA/qVWZmIrMQhNjt3nOva540BZPvfBJfWBPL1Hp6jIYRY8H+o+ffsBWhAXPliyBbe/QWbEsXYLkKWDYaWlr1NyLIKo3xsuBjo2MNEglS7mw1BJCxu2m69/1fIZQIKcuA0qf9tbvMKs4qyWWczfZGnlLBd4Z1WSJ5/IdjD4LFRxYNsV0fA1cRiKUDV+dYtZtpMqAyNZssT+hcfxhZl243lgulT8qouv2H8/Lg7WcpRjRxYOAWV2bPiT/C8miNPBnWCONlY5Wa5jUozY6mmIOOKoiSNDe/Fbwfxd7plyuM/SVrxKP2aDKNEyM2n9H45SzGhb/T3B4fP8fiWJU3hcBma638I9lnw37X9bRMWxD9PfuMFerb0gMQc0yh5YX27KiAEZW4TDrQZkkdW3qI3viAfbcAb+lk+F1kL5Pmd9UIOoZrDckhBsFwJmvViEnQLSIn3SkZ+HNeaqtOr1cO+Hd4roedAfbJDS/xSDZc8A+iATWhjppKEWvSSsuestU9LI+CZ404Qdl/Z/Giw5sWXCGqTxVeyrWCgWFwaDNeNtwBMPuJrBrUMkl3dg3E304QSraPChUtkmAO+u7YXpZdOAwYsGn7/QChKVdXHc50bptJvE7GHG3xt3h/Ci3GADtJc9XtVrEbc77eSqPrc3nqd65iaPZEIxzP1bcfoLNBAa22lMmRouMI86B3YUmG3tjr8hlNFozoA2gfyqkkzfLPSkNm9noNo87Hua7FhlVcy0ENh9Awby8dUfWHFeY6yRMO67JsnJvpu1W4YwUpe9C0qhl+u2LJyLeJiBCEDlxoswFJEYtjSZ3tj4KUeQs7DHEzC4BVTI8BmakqCGGfvngp6uv77t9eWrqaBcmxsiACjlKMCAnppgehZI0LIvVMAiZ31KF6uKs64Tf9kkW+jlYp1gAeZfL7+zS0xzxer+dFA+y6u8uSu5YTqaRG+kLxeMoTrPAmwllAGf2wZLsxUautojO/Xf3mvLtLuj3qMXZ147fLU9RiTmBFa0jeuVPuOfI3QimKiplPxaHoCuVY+EnbV4zrDPEwTb+czLqgMkMZewB388lvQ5JN6XmpFS0Y6Y0FNgzREjnRdSTjtP0qGyQrhAbYFnmVGk/7AAhOjtfcDNiDUWrj3rRPwIfvreUP6dZB4/E49f4/onl61jDV8orxmHbw8AEvBgOCFxrfvxQxs++T3NE+SLTnwxTYl12hVqfBnrX0xXj+n1vZFnuPx0tcn9pCkGbI1N1nw9QlTGLWpVObhG/t8wTBqTeQYdOH17qWesArE3v6seAf3pbgWZNBL6nvQoC24UUphZeuHGdEPxccVuCGCbgFNwaBevUPuhm2dJJZzOm8+5I9ri69uLMAJJR5/Zj1Tb8izXI3iarMXrXWjUL9pyeR6kU7uVbUkwLMaRfT+OW8fZq9mDAm3WdOP7g6qbLpaBGjKL76UxJLNQS8Mlf8wnQkK9kyf4hcQTngoKXAipWF/3n+Hyl4RjPkzsSKgb1hzU37n94/jUKYlD0uu273zLb510XXL4EbvQyYizPkDfoVD8dxZUpTRbgbXTq1nvCbTC/nghEX2z/0trDV8aZJUL9o0vb2LTMure/HXDM9QfvSzoovvp2SgcvLkK7sphpr9ddP6Tri7YwVZ9wLHKja/6SNy1x/AainjB/WGLyNDszNPSv+qDOShhx/G/XHCb2f1icPmZ5GmoiXFNcazRCelh19zIUzfEXzq/zkUmZ"
          - name: "infranodes.enabled"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-ocp-internal-registry
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      targetRevision: "*"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.play.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.play.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "play"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
        group: apik10.kasten.io
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cicd-tools
      targetRevision: "*"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.apps.play.gepaplexx.com"
          - name: "argo_workflows.server.ingress.hosts[0]"
            value: "workflows.apps.play.gepaplexx.com"
          - name: "argo_workflows.server.ingress.tls[0].hosts[0]"
            value: "workflows.apps.play.gepaplexx.com"
          - name: "argo_workflows.server.ingress.tls[0].secretName"
            value: "workflows.apps.play.gepaplexx.com-tls"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.apps.play.gepaplexx.com"
          - name: "sealedSecret.postgresql.password"
            value: "AgBJ7vWAsvjju5UoNEDyMi1+NHydrvYBbpswJ0metAPhaT2lrxtJiMWvSZR4+kWJWgYHSfRZQYfZIONubEC1a3FAF53K4hqUuaZeBL/YjlwZ3OVgQnFKyh5UIbSnDMC4+HR3YAE3k874su3q6Kch8rBrqgASjuu+A2hV5fEI/j/DjgdPxh4FxM9T2RyyoFikbX0AzAzsheuvqsoa9ETfgqfJn0v0Ju0n6bL4Wvo3hl0ujqV7FGZMlM8FWJ9nXcM5pPDwPp8/Gc9iFZc/Of2qhzU1yUOpaShyBw4nfNB9ZcD//9Lre0Z8q5fTdtCcyRvT4VL/myHO+4hRyNcFy9/Q6nXhFjC1itKppS57f0tPDdqY9d3QVScif+RpKRs3+6LDDJUJ152ymxClDkdx2n7TpxB+fn3XKh7f/IZnl/erXMmo8eJHLuCJGGXHVevzpPurjeF99LYW879RS/JJEKqKhjevVcmCMQSJt+Fm52JmpIdg8CLOziw8a5TV5An/g2Nqrv4FJBAPT2Wyfx3AtZV5gJBRwqKasnFECCR1ZK1ibvjc3RvkdqdIRke36fz8xkMgcIdX9Ruox7Fess38QLRnJoKpBvQHHfRaxB5r5A4qlUQ+HfLLDZ0JtO7M3A9TwNrkl0gSo/GVQ2l3YYMvs6IcCc7QQWg18uQQnY1nKOrMQd7En4xZRBOUKGSbyAKgEjeEVkIRcN+0vQ=="
          - name: "sealedSecret.postgresql.postgresPassword"
            value: "AgAhpIUHUN3TKWI5K2yIn7CyQvVejZQZLI7UgTNg1t0I9E9MWftRAX8TSUu3Hst2Rh+HPx3z0yE+GuDmKH2siWc6ZBAkNWMIZYDDDYUgLVGNNebh8LMBskmgqt6mGKv1/4x2JH+q+2cqmclNLQ4THGeZF+e9rdLWkDidVdy0O+FBG6TrR86YYGsb0/nBW0uYR/Kt0J1pUOwwuxgmtIG8wMpIbJgGv9heCdAONS8piIlb4eW1L4iaHPnbLqGszx+amTvqnTXi2YqlV1V4vAFuUE192edbZmXZ1mXLLn24rmANOHa3jzrpfHtYHDS/AgqYVKVYtip2ThKajkq9T3f/PlxwhmfVjEYBQcBu+I1zRR22MZ3rI2R2sV/zPQwWeqCya7o3H+AW0t9BiVSz9djvHhBVHgJ4V32CYO+qqfNadwq7zum3UK89oGdJTfiPJ51wZSBuabp//wWIiNsVoMs1paWpVnWoMKf0bosFpTKxB6uyJC35b3QBYzccuiviN272LDmAm0aj2EwdEo1nWWiZDsyDw+mTBPt84729hGV3sz+8g5x9k929+mK97H28zIdZzhHY0yVOLAer1jsKDygUUxZGcPxOua6zXpqP3DTESvNtkrnaBFJxbeR1HhYRMl2HE1SP5GEEIfHXB5D0XxN4NekD28x57jRecsfLvd/YHKVzzfdTld0Ae8EjXm3FtEe3K2l0X90big=="
          - name: "sealedSecret.postgresql.username"
            value: "AgANzRJhzo5xONwx25DOddtUToH8sS4BjAwE6AFB4opKtKSv+eJMgh61p2ABGY7Ivtqt0CzWiFg+51Q60QaJ8t/vVBwwImPA/TVfmhBnLnnmuV/jSG1VfvjrfYSoPfKtXhJTiSjsmZcqEzt4XKiRVB6eCCZQ8wOHp7Q6BDz/2Vg/q0kU/7O9KM79c2356DboKzDhOwjk4NEItOiqXxGNCiQ7gWb42KEaHUbqXhxIGVpTgt8HBaP8eZ5C6oPTfi+bOnhG4U1WP21UQn467GMDOATeunzNMNImKS7flW+A/qlTVMQugoMz9NEtUdDIUAEKMpgXF2ibMDQMqVkKFjnyt+FX5KNYfpGSIimy+32Anb09oIfIgpQknNn15dFLqkANZWw7YFBTCe6Q1eG4EkKfvTVjG09He56AMOn/t+2oVv1h7eOcra1i2mUvCI2ZIoGmaqI/nDb8XXtGu9rwR6cNs42ilogJ6pl86lcdzx1H/Ju+C67m7UB/MWEYtkrOxE4UQRmTo82hrBqPpunCo1hBiPVGY5SZKfwis1UJLTb6NvSFZHqx6Tm6Ln5jK/WCAOosmphGWHydehSgwpnKb39b4LU7bc9uJl3CGCIpgnkUsHNvznwrdCxSC+WbPxpDNNrfbziy+xL9wfd/nJRYUSmORCYvcejFZh1R6xkXEdY5UoS5Z3oF2iwJwD/4lFYBDQkP1YGWMqeJOnjzrA=="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/play/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true