project:
  create: false
  name: gepaplexx

applications:
  ####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-update-checker
      targetRevision: "1.2.1"
      helm:
        parameters:
          - name: "clustername"
            value: "steppe"
          - name: "consoleUrl"
            value: "console.apps.steppe.gepaplexx.com"
          - name: "slack.channel"
            value: "AgBIPG9Zo8SxwkZbayJT7kKCFT8EETzn6qmwPLmV3H9KOgxUWsPdhKQZC0Qnkc6dGJk7jv/rDhnzzYJ62hSvIvgKh5FQQkOyIbAvWhIUeO7xSWQK38UhULmlIdnhMoo1NVbmdWCM/VyF8N4HizqeD2c6UnTmJuwbWR7vGFzxD622G+arsZ4Kx5mBGnfcNsDcSu2yiq3R47m3iB+KNgr3M9aJFAsQaWHiiufgFTTqJicNAfo3FjzrPPvOd57B/SZuL0QXOlxUMVzHA/RGn5/2J+LWjnbOXH4d3d6zwmgv0mLAor86hn301y3ZLVXqUaphaMsPuVv8/KEEpTYu1uyw10cCMSr8wlCa53O7RdgA3IGdjHi0y9qZxs+HFzuRVhWOPmcADN3iUiJV7FZtW0C2N7HfdO3V1365D2BXuT23b4OzGplm2oj02XKeNAN9cj2/oWTVx4tSyojr9L/5tnwHlN+Sg21ACiqhRoAmQRe4K6YO+YSDne6+hE3aDPGAdNQQHUSHe8JHhaxzS9DiHj/R/5waLaSrm9TWlT2t1gDqehAN1aPra/QI+ETJtVAA+eapv5PUq7sWRyjTdEBMEOLbClIwRcHQKj/fslNhYEv0ZLAN0JeyBJwmsXtth89m5wVDPz+0WIeH2JbkBr3xLcYXR4OY7No+YA/jdtCDntyXH4GmnLIW55z7fE0MmbxtniT2ryHiiM4vrRhPC90nNJykMaxrBP9+Kc4HP10Gbnf7yGlXfuDzP1sWPpDtImPTe8GMpdGqXntLlnS0FXOGeMVNIoFfqxT5GGlNmZN5xuaWwqNhrIo="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging-instance
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-instance
      targetRevision: "1.3.0"
      helm:
        parameters:
          - name: "elasticsearch.resources.requests.memory"
            value: "10Gi" # FIXME
          - name: "elasticsearch.resources.limits.memory"
            value: "10Gi" # FIXME
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### CLUSTER-LOGGING-EVENTROUTER #######################
  clusterLoggingEventrouter:
    name: cluster-logging-eventrouter
    enabled: true
    destination:
      namespace: openshift-logging
      create: false
    argoProject: gepaplexx
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-logging-eventrouter
      targetRevision: "0.1.1"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-monitoring
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cluster-monitoring-config
      targetRevision: "1.2.2"
      helm:
        parameters:
          - name: "alertmanager.config"
            value: "AgBpLi6aAQpvGuKqEAiIzR327ojDLOl3razVf/Al4rfwBX0vAeV2RjpGS+WxqMCHSKf77IqRZorNjWoPqHyB6h+C+79+66N9Id1HpcWWxYo4stlxE82VmjOiAFTfFMKDvRfNA0Rod9r4BLXH8QISay/KqfyAJOvVz48LMKoZZILZYY2+o+AFuP+MmBTcoqCgzLQsiXwICR0H5kDFg4DTPJu8/+GvJQXjSs7LfBRjIt9eH7M4Q+ATPlbgMGnJCUGEqZjJd9FuMVAk1Cysyzcq3nnR/balvcL2xz8BHeKCV7mviDm0RfKG2DrbdkA9EASoPVkqCpIShtyYovee5AxGUaqmMU3u+TnDEa6ia4xnQODhswB6+jHNfRDFdfOHOAm0h5MrVc4gztikSw4Xa48BeC174r9daex6G9FxQGZkSdT4sn+Z/7/uAK9n4zBByGr2Po0BOa9KrxTxLOIUYa3mDp5zj1hAYkLrhsIhlmqobNzvqmRsUm0EWXWWIDVmwK99dZDAQLIoXVFTYkXyv8Kni32s/QOdVa1W9gmbjBRqWy7ImczrUPz1P0elwS5pl9wM/ylcujCMRBcxHKWNDtmUOpspgu9oqR58n0KrAsHS7YkPfqmN6ONmztcyoKc/JryZcU6y4XBvNc0PLYsuCe5Sdv8lh0v4iKtW8UCFw/aR4LQn25e892VtvZnxECsabBjk2rCf/qHkCO6cvC0sneugKA8F7l2M0bVhzHl42607Uqa900H4JDjsvCLGO4QcDJDGnYyLG1NXIFtDVvRNmOWk/7X4n6tuKUuFgQJnsQc8OFXg6u75R1CykrMUw+OPMPj7Mlo5z+eQOdquQ3rp/hvYgVSdvRWVzkuc52sWKqvLL5+0JznpRY5+EmlG5U8Jspk0OPokOyD4BnSlA1m0pH1NSyiHOoPwcop3Sc16qbAvW6yxhsshuuuCFLGBY3HXKI/w6gmDoP1wNjbwUqJkQPZ9MXo38h8HoB8AYYl7BkUknknxFnaNHLvqcQHht8H0cMCGiWwxu2OJBBOQl1vfqtlJkC92xsdpejc5Cu8bpQtH/0nVWK/bKHzGsRcX1EhLmIpnr15SN3bOB51wwtrQfb+QPaikLMkJFo1P1+OJuI1ILBkiyFht+g3Gr32NndVFGtY7IycTmz1/eK3WBrJbvG/ly3WW4H+OJsg1imJjDdJzKzgdVPuJ+CFvpxFB2EOGbrbRVOaBNh5q12c2yEL/4CUyAl7lbPNySoWXeWrc3nHnb9zau1W7ZqrR9qBBjghikWXhKo2EXioqfkNtXh72PfeTRSTO6AfWk1zP0LsMvSqZKufkyTK761XPGafGSEg12K2m+o1mkHiRyd5wRsSKx+BUE55BYmz2Lf+HyHRzhr6kYdmcw3lzsT7TDlleGmVh859qzH0ETm8C9s8veo+6C/mZBn9weN+2IdvM7eTx0uM0LR5r1Yv1c72EGH+nbm+2GKB7mMEhfCr6K/Y8/kGVdpD2+JMNocKpDmN5iVVFWG3wk0SwDdHQYfCM0CwaTufYi2xQRO3aOe7u00uCxIexxeCAHwoYBWvsN+0I9cQfYvSURmJTjYbMqk4a+d+kEeURzSXjAimlHHp0YTbtwMC5XeJFHl9ChIJlOTIvbQhlZpEYtyA8Qqfcy4gksdBqeVfWToNKp/4cvmyUCeD2qFQZr6k5UpQe01X78qugFdThKK/4T6I3ZzXeQUl/QJjWHsRqHdPIX7k7lx4l6aa1/t6UkeWlf9HAy6vmTXWnFKxfYbrmptBUwSEK9TUOd/ftbPD0lUnZ870MqlkVmgKdGv2PHrOdrcoCE0GFgcWU2N1AC/JYBMiAFOjSul4wEmg8GDGOEsli9vIvN2OeXL3fsKRhoH9Kj+uktCJJZygabcPHIxAkjjMBFQdLnc5VMScR3wYN2LuKMXC4yloF+PlJTPt6Ws0SrqC3ozVU180cS7T3WIWmmUuCtss7533HiPzYzGTaqC8hkc21gf+/KPXisxfU0a2LdPjkPaDSQ8Viq+sAXnr0BIirQpArz7ZdftaTn3cF0BYwMe9x/Okj1V+8/IZzdr13K0RKUmjeSe+kf4cMITenIhpv8+GDJjUJ0Zf4MkgdLihLK7q+LPvfMTnYlrTxdqnSPU7FLnhS5A9c+xzIAzYVlzZn7D3/km4pHhLxowL/P9xhT3C+sgDdJ8vDse+PDNK1kDafTYUob5rFjnmb2JhrtlZFR4IRgyaMoD9fkAgVvyMAVaMV5LFrpkPGPzly/+30sLkh/KGmUHFD7RQoExAQVhvMHqAsoTHLzLHacjHQWuV9VshrMxXJSqN00wfaooxdCJxg8vMAYJ6T6RpxU0NaaZU5LzbETGsy0S5S5DMJdv1MnCTo/vdwfISo43sPqZAIGZOZgVWYwoo44DaO7FESflvQQbF0TGpEljc/N7LV04f3Y0SSTlXz1gi3xX5pKiLl/MA99GZEmum47gb/rVdonQYOPrR6HlrobkOhV8YwTfmq6tTjHRJQYmiIAb8poLjzQIplKGOx5nc28LSoYWznqHFubkkwsNZxHn1C8d/zTuoNKI8SvoicJE7+7zsizwtixqqCp+X8aptPniZprqvLIGQ3IeZ2oaJ9oYqfHLjKbzRhj4yTGClaH7665lZZCdBwGgZ5/rViUV87KV+ncPsy38fRb9os+UO6uadRyk3qUpeLvJZlF9a5zzXAF90NAFDto2zuQApH2dArJG3dDHdpyMRa/5zBN9avvbwSgk/vzfd61scmScB38zUI/sKVN2prABiQit547YNL5Sef/GyaOMv8eOw="
          - name: "infranodes.enabled"
            value: "true"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### OPENSHIFT IMAGE REGISTRY ######################
  internalRegistry:
    name: openshift-registry
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gp-infrastructure
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-ocp-internal-registry
      targetRevision: "1.1.0"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 BACKUP ######################
  kasten-instance:
    name: k10
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      targetRevision: "0.0.3"
      chart: "gp-kasten-instance"
      helm:
        parameters:
          - name: "kasten.auth.clusterApiURL"
            value: "api.steppe.gepaplexx.com"
          - name: "kasten.route.host"
            value: "kasten.apps.steppe.gepaplexx.com"
          - name: "kasten.clusterName"
            value: "steppe"
    ignoreDifferences:
      - jsonPointers:
          - /spec/auth/openshift/clientSecret
        kind: K10
        group: apik10.kasten.io
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-TOOLS ######################
  gepaplexx-cicd-tools:
    name: gepaplexx-cicd-tools
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cicd-tools
      targetRevision: "0.3.5"
      helm:
        parameters:
          - name: "argocd.route.hostname"
            value: "argocd.apps.steppe.gepaplexx.com"
          - name: "argo_workflows.ingress.hostname"
            value: "workflows.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.hosts[0]"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].hosts[0]"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "argo_rollouts.dashboard.ingress.tls[0].secretName"
            value: "rollouts.apps.steppe.gepaplexx.com"
          - name: "sealedSecrets.postgresql.password"
            value: "AgBOMsWEqSwd6lxYLmAZ4WyGAboHcn3HT0D96ui/jcn6Vr4w9Vjw9MhEbKGw1YOsgby8mKptszRoMxmEnL5wk0lpUYlSuurad0fstLqqSd6NG+4vqAOH6vZKgaZ81jNmW7V/mHB+mVTN+6j99NATkKXeJzWoZmqC6Q5p7Ir/mxJxYpXmG2QJhmyAapsTfJJ3DFVBU7RZ20MJz3w5m8EYgbbm3WOy8B4OdOdaDHR8l8VE0zOO42QPn7fDsu/+fo/RrE4hosdWpiJrNyOGctgVd5Y6HSHENvl9swyObdDZ4NEX7vuAmP94TO9FIYIQbAVrzfWFGXsRdSBFMzNMl4GAopICbZuYPdvnm4UHRr4JS5+Rk3YljsVccAtzpM9LCDcR9tpSVEezaBE8UZS3qgzSCklO3yjxl3lSqIpyqzIMCsKyYmZYjqxDfQqD4uB1K8CnDujjQ6ib6pkf4/jckzD0/LW5SvjsUK5+m7PeG9/BgNv+V4Y4CHUhzSH/nt/Wjz/t4LSkWyzK4o7GmDKIPgfErOawELnqYTbdNdsBMALGKK9luSAsaod5PGreBKGdqe5qTCaOhUXfqm5a01hwwpV7LXGaznwI1w1wc2oIYM5lR0biH9F42c9+l4af4Hq8Ed8+J6i0vu/tf0RlzRvH6JpjM0I/poE638FaCCHrPaSwGtDurPKKHNOsJ6clpoxUidhDkqz1rOrE/AX+crU="
          - name: "sealedSecrets.postgresql.postgresPassword"
            value: "AgA1XBm6eO5U4WcEKxom15GxeO7wpWJlYZ2HG7zVnPAH54kh4vsTLpzLm0Pr3GjRYEKU7sRa7i8QJH/ZVEyZKD+fYogafKETCmcq9PEIhg+iK82UbSmxI5I1knrx88llzVw1u3xa3huXXLfNAFQUFO+c/2xz11zaqjOym531uvYMgA1ZCMo01YqHrzYj+tEhLGvZO8xVQXCWvmam8f4ziMGO9lShJF7I3WY6sjk7pL5pFOCoRltUZjboYfbiGh7LPc+fZIdC3+68xFg0XYCBlI2tg5cdLKuHeRuw3KGCfQaTVQmbhFUYNJML+f6ph74ZoJuXCRjWM1g5AWxBb7JGqrZ+mwI4rh5LvbFw17MsPwLjQLW5pqu+/P2c/wYvbNadrSp4o2e++qvKIgc4L4sOOz2iehSsHDHMOOlFS1DsD2v6LGjDW+qBkWLN768OUy4kbQVs8VeyKNAc/fYvP2gx5Tox4hnSQzIfdD27y/I0EXCpZeB7otLT9ZtgYhtbfOVByry4L++EP4maoBaT1BS4cDmeYORZwZPooCdSPtYGYcEn/bGVRYVIMVXiaD0blwW7haN6yf8tLYTp4gaS4RBoVa9EqNAguDMj6kvqCg0iSlfCU8XVrOLBY+zGelBolz/sshRk6UAAJzMbTjafysnqfDTvDfvZy1yzHJG2lDqKslc7JerOjnY5CQMTiHONChUVh6grNcXq3rwKWcQ="
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTS ######################
  gepaplexx-cicd-argo-events:
    name: gp-cicd-argo-events
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-tools
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gp-cicd-argo-events
      targetRevision: "0.3.0"
      helm:
        skipCrds: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD-EVENTBUS ######################
  gepaplexx-cicd-eventbus:
    name: gepaplexx-cicd-eventbus
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: gepaplexx-cicd-eventbus
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-charts/"
      chart: gepaplexx-cicd-eventbus
      targetRevision: "0.1.1"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ##################### GEPAPLEXX-CICD ######################
  gepaplexx-cicd:
    name: gepaplexx-cicd
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-gitops
      create: false
    source:
      repoURL: "git@github.com:gepaplexx/gepaplexx-cicd.git"
      targetRevision: "main"
      path: "clusters/steppe/applications"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true