project:
  create: false
  name: gepaplexx

applications:
########################## ROOK/CEPH INSTANCE ##########################
  rookCephInstance:
    name: rook-ceph-instance
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: rook-ceph
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-storage-cephcluster
      targetRevision: "*"
    ignoreDifferences:
      - jsonPointers:
          - /spec/monitoring/
        kind: CephCluster
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################### CLUSTER-LOGGING OPERATOR ##########################
  clusterLoggingOperator:
    name: cluster-logging-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: openshift-logging
      create: false
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      chart: gp-cluster-logging-operator
      targetRevision: "*"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### KASTEN K10 OPERATOR ######################
  kasten-operator:
    name: k10-operator
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: k10
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-kasten-operator"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  ####################### NFS-STORAGE-PROVISIONER ######################
  nfs-provisioner:
    name: nfs
    enabled: true
    argoProject: gepaplexx
    destination:
      namespace: nfs-storage-provisioner
      create: true
    source:
      repoURL: "https://gepaplexx.github.io/gp-helm-chart-development/"
      targetRevision: "*"
      chart: "gp-nfs-provisioner"
      helm:
        parameters:
          - name: "provisioner.nfs.path"
            value: "/data/col1/play"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true